### PR TITLE
Fix die() when source book is missing (fixes #285)

### LINKED ISSUE #285: Cloned content diff tool fails badly when source book is missing
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

`Pressbooks\Book\Helpers\get_source_book_toc()` needs error handling:

```
Error: Uncaught exception 'Error' with message 'Cannot use object of type WP_Error as array' in /srv/www/pressbooks.test/web/app/themes/pressbooks-book/inc/helpers/namespace.php:322
in Pressbooks\Book\Helpers\get_source_book_toc called at /srv/www/pressbooks.test/web/app/themes/pressbooks-book/partials/content-difftool.php (9)
in include called at /srv/www/pressbooks.test/web/app/themes/pressbooks-book/single.php (29)
in include called at /srv/www/pressbooks.test/web/wp/wp-includes/template-loader.php (74)
in require_once called at /srv/www/pressbooks.test/web/wp/wp-blog-header.php (19)
in require called at /srv/www/pressbooks.test/web/index.php (5)
```

See also:

```
E_WARNING: Illegal string offset 'name'
in include called at /srv/www/pressbooks.test/web/app/themes/pressbooks-book/single.php (29)
in include called at /srv/www/pressbooks.test/web/wp/wp-includes/template-loader.php (74)
in require_once called at /srv/www/pressbooks.test/web/wp/wp-blog-header.php (19)
in require called at /srv/www/pressbooks.test/web/index.php (5)
```

### Steps to Reproduce

1. Try to compare chapter in a cloned book with a source chapter which is not accessible.

**Expected behavior:** Graceful failure.

**Actual behavior:** Graceless failure.

### System Information

McLuhan: 2.6.0-dev

### PR DESCRIPTION
**Pull request by connerbw**

### CODE REVIEW

File: inc/helpers/namespace.php [hunk 1]
```diff
@@ -276,7 +276,7 @@ function get_source_book( $book_url, $checked = [] ) {
  *
  * @param string $book_url The URL of the book to trace.
  *
- * @return array The metadata array.
+ * @return string The metadata array.
```
Comment (greatislander) [inline inc/helpers/namespace.php]: The `@return` type is correct but the description isn't:

```suggestion
 * @return string The URL of the book's original source.
```

File: inc/helpers/namespace.php [hunk 2]
```diff
@@ -294,7 +294,7 @@ function get_source_book_url( $book_url ) {
  *
  * @param string $source_url The URL of the original book.
  *
- * @return array The metadata array.
+ * @return array|false The metadata array.
```
Comment (greatislander) [inline inc/helpers/namespace.php]:
```suggestion
 * @return array|false The metadata array, or false if no metadata was found.
```

File: inc/helpers/namespace.php [hunk 3]
```diff
@@ -317,12 +317,17 @@ function get_source_book_meta( $source_url ) {
...
```
Comment (greatislander) [inline inc/helpers/namespace.php]:
```suggestion
 * @return array|false The metadata array, or false if no metadata was found.
```

File: inc/helpers/namespace.php [hunk 4]
```diff
@@ -360,7 +365,7 @@ function get_book_authors( $metadata ) {
  * @param string $needle The URL of the cloned section.
  * @param array $haystack The TOC array for the source book.
  *
- * @return array
+ * @return array|false
```
Comment (greatislander) [inline inc/helpers/namespace.php]:
```suggestion
 * @return array|false The section array from the source book TOC, or false if none was found.
```
