### PR TITLE
Hide the title if pb_show_title is unchecked  (fix #148)

### LINKED ISSUE #148: Title displays in webbook when "Show Title" is unchecked: clarify behaviour
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-book/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Chapters selected to show in web, but not selected to "Show Title" still display the title in web. Not sure if this is expected behaviour — if so, we should change "Show Title" to "Show Title in Exports." Replicated issue across themes.

### Steps to Reproduce

1. Create a chapter, select to "Show in Web" only.
2. View chapter in webbook.

**Expected behavior:** Title does not display in webbook. 

**Actual behavior:** Title does display in webbook.

### System Information

McLuhan 2.1.0

### PR DESCRIPTION
**Pull request by connerbw**

### CODE REVIEW

File: partials/content-single-legacy.php [hunk 1]
```diff
@@ -1,8 +1,11 @@
 <h2 class="entry-title"><?php
-if ( $number ) {
-	echo "<span>$number</span>  ";
+if ( get_post_meta( $post->ID, 'pb_show_title', true ) ) {
+	if ( $number ) {
```
Comment (greatislander) [inline partials/content-single-legacy.php]: Sorry, unclear on my part. The number should be unaffected by this change.

File: partials/content-single.php [hunk 2]
```diff
@@ -1,10 +1,13 @@
 <section data-type="<?php echo $datatype; ?>" <?php post_class( pb_get_section_type( $post ) ); ?>>
 <header>
 	<h1 class="entry-title"><?php
-	if ( $number ) {
-		echo "<span>$number</span> ";
+	if ( get_post_meta( $post->ID, 'pb_show_title', true ) ) {
+		if ( $number ) {
```
Comment (greatislander) [inline partials/content-single.php]: Same here.
